### ISSUE TITLE
Word?

### ISSUE THREAD

**Issue by davidpassmore** [tomstafford/rmarkdown_apa#1]
Tom,

Great repo. Just what I am looking for.

My Word doc is not formed as your example. There are some style differences, which can be handled with Word styles. Tables, exponentiation, and references will require some editing if I use this. I attach the Word output I produced,

Able to integrate APA 7?

Thanks,
[example_manuscript1.docx](https://github.com/tomstafford/rmarkdown_apa/files/9125526/example_manuscript1.docx)

David

**Comment by tomstafford** [comment]
That is a papaja issue, which I am not equiped to help with. http://frederikaust.com/papaja_man/limitations.html#microsoft-word-documents

**Comment by davidpassmore** [comment]
OK, thanks for response.

David

**Comment by tomstafford** [comment]
Sorry I can't offer more help, but this is one for the original package
developers (and looks like it is something of a known issue)
